
public class FibonacciQuestion {


    public static void main(String[] args) {
        //The fibonacci number is generated by adding the previous two numbers
        // F(N) = F(N-1) + F(N-2). We can use recursion to print fibonacci series.

        // 0 1 1 2 3 5

        int a = 0;
        int b = 1;
        int c = 1; // c = a + b
        for (int i = 0; i < 9; i++) {//5
            System.out.print(a + " ");//0 1 1 2 3
            a = b;       //1 1 2 3
            b = c;       //1 2 3 5
            c = a + b;   //2 3 5 8   num1 num2 (num1+num2) num4                 num5
            //                        .................   ((num1+num2)+num2)
            //.................................................... (((num1+num2)+num2)+(num1+num2))

        }
        System.out.println();
        System.out.println("---------------second method----------------");
        int x = 0;
        int y = 1;
        int z = 0;

        for (int i = 0; i < 9; i++) {//5
            System.out.print(z + " ");//0 1 1 2 3
            x = y;      //1 0 1 1
            y = z;      //0 1 1 2
            z = x + y;  //1 1 2 3

        }

        System.out.println("\n---------------Third method-Array---------------");

        int num = 9;
        fib(num);
    }

    public static void fib(int num) {

        int[] nums = new int[num];
        nums[0] = 0;
        nums[1] = 1;
        System.out.print(nums[0] + " " + nums[1] + " ");
        for (int i = 2; i <= num-1; i++) {

            nums[i] = nums[i - 2] + nums[i - 1];
            System.out.print(nums[i] + " ");
        }


        System.out.println("\n---------------Fourth method----------------");

        int num1 = 0;
        int num2 = 1;
        int sum;

        System.out.print(num1+" "+ num2+" ");

        for (int i = 2; i < 9; i++) {
            sum = num1 + num2;
            num1 = num2;
            num2 = sum;
            System.out.print(sum+" ");


        }



    }
}

